//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace ChangeControl.myAD {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ADInfoSoap", Namespace="http://tempuri.org/")]
    public partial class ADInfo : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ChkAuthOperationCompleted;
        
        private System.Threading.SendOrPostCallback ChkEmailOperationCompleted;
        
        private System.Threading.SendOrPostCallback ChkDeptOperationCompleted;
        
        private System.Threading.SendOrPostCallback ChkFullNameOperationCompleted;
        
        private System.Threading.SendOrPostCallback ChkNameOperationCompleted;
        
        private System.Threading.SendOrPostCallback ChkSurNameOperationCompleted;
        
        private System.Threading.SendOrPostCallback ChkPositionOperationCompleted;
        
        private System.Threading.SendOrPostCallback ChkSectionOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ADInfo() {
            this.Url = global::ChangeControl.Properties.Settings.Default.ChangeControl_myAD_ADInfo;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ChkAuthCompletedEventHandler ChkAuthCompleted;
        
        /// <remarks/>
        public event ChkEmailCompletedEventHandler ChkEmailCompleted;
        
        /// <remarks/>
        public event ChkDeptCompletedEventHandler ChkDeptCompleted;
        
        /// <remarks/>
        public event ChkFullNameCompletedEventHandler ChkFullNameCompleted;
        
        /// <remarks/>
        public event ChkNameCompletedEventHandler ChkNameCompleted;
        
        /// <remarks/>
        public event ChkSurNameCompletedEventHandler ChkSurNameCompleted;
        
        /// <remarks/>
        public event ChkPositionCompletedEventHandler ChkPositionCompleted;
        
        /// <remarks/>
        public event ChkSectionCompletedEventHandler ChkSectionCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ChkAuth", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool ChkAuth(string user, string pass) {
            object[] results = this.Invoke("ChkAuth", new object[] {
                        user,
                        pass});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void ChkAuthAsync(string user, string pass) {
            this.ChkAuthAsync(user, pass, null);
        }
        
        /// <remarks/>
        public void ChkAuthAsync(string user, string pass, object userState) {
            if ((this.ChkAuthOperationCompleted == null)) {
                this.ChkAuthOperationCompleted = new System.Threading.SendOrPostCallback(this.OnChkAuthOperationCompleted);
            }
            this.InvokeAsync("ChkAuth", new object[] {
                        user,
                        pass}, this.ChkAuthOperationCompleted, userState);
        }
        
        private void OnChkAuthOperationCompleted(object arg) {
            if ((this.ChkAuthCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ChkAuthCompleted(this, new ChkAuthCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ChkEmail", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ChkEmail(string username) {
            object[] results = this.Invoke("ChkEmail", new object[] {
                        username});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ChkEmailAsync(string username) {
            this.ChkEmailAsync(username, null);
        }
        
        /// <remarks/>
        public void ChkEmailAsync(string username, object userState) {
            if ((this.ChkEmailOperationCompleted == null)) {
                this.ChkEmailOperationCompleted = new System.Threading.SendOrPostCallback(this.OnChkEmailOperationCompleted);
            }
            this.InvokeAsync("ChkEmail", new object[] {
                        username}, this.ChkEmailOperationCompleted, userState);
        }
        
        private void OnChkEmailOperationCompleted(object arg) {
            if ((this.ChkEmailCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ChkEmailCompleted(this, new ChkEmailCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ChkDept", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ChkDept(string username) {
            object[] results = this.Invoke("ChkDept", new object[] {
                        username});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ChkDeptAsync(string username) {
            this.ChkDeptAsync(username, null);
        }
        
        /// <remarks/>
        public void ChkDeptAsync(string username, object userState) {
            if ((this.ChkDeptOperationCompleted == null)) {
                this.ChkDeptOperationCompleted = new System.Threading.SendOrPostCallback(this.OnChkDeptOperationCompleted);
            }
            this.InvokeAsync("ChkDept", new object[] {
                        username}, this.ChkDeptOperationCompleted, userState);
        }
        
        private void OnChkDeptOperationCompleted(object arg) {
            if ((this.ChkDeptCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ChkDeptCompleted(this, new ChkDeptCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ChkFullName", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ChkFullName(string username) {
            object[] results = this.Invoke("ChkFullName", new object[] {
                        username});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ChkFullNameAsync(string username) {
            this.ChkFullNameAsync(username, null);
        }
        
        /// <remarks/>
        public void ChkFullNameAsync(string username, object userState) {
            if ((this.ChkFullNameOperationCompleted == null)) {
                this.ChkFullNameOperationCompleted = new System.Threading.SendOrPostCallback(this.OnChkFullNameOperationCompleted);
            }
            this.InvokeAsync("ChkFullName", new object[] {
                        username}, this.ChkFullNameOperationCompleted, userState);
        }
        
        private void OnChkFullNameOperationCompleted(object arg) {
            if ((this.ChkFullNameCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ChkFullNameCompleted(this, new ChkFullNameCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ChkName", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ChkName(string username) {
            object[] results = this.Invoke("ChkName", new object[] {
                        username});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ChkNameAsync(string username) {
            this.ChkNameAsync(username, null);
        }
        
        /// <remarks/>
        public void ChkNameAsync(string username, object userState) {
            if ((this.ChkNameOperationCompleted == null)) {
                this.ChkNameOperationCompleted = new System.Threading.SendOrPostCallback(this.OnChkNameOperationCompleted);
            }
            this.InvokeAsync("ChkName", new object[] {
                        username}, this.ChkNameOperationCompleted, userState);
        }
        
        private void OnChkNameOperationCompleted(object arg) {
            if ((this.ChkNameCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ChkNameCompleted(this, new ChkNameCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ChkSurName", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ChkSurName(string username) {
            object[] results = this.Invoke("ChkSurName", new object[] {
                        username});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ChkSurNameAsync(string username) {
            this.ChkSurNameAsync(username, null);
        }
        
        /// <remarks/>
        public void ChkSurNameAsync(string username, object userState) {
            if ((this.ChkSurNameOperationCompleted == null)) {
                this.ChkSurNameOperationCompleted = new System.Threading.SendOrPostCallback(this.OnChkSurNameOperationCompleted);
            }
            this.InvokeAsync("ChkSurName", new object[] {
                        username}, this.ChkSurNameOperationCompleted, userState);
        }
        
        private void OnChkSurNameOperationCompleted(object arg) {
            if ((this.ChkSurNameCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ChkSurNameCompleted(this, new ChkSurNameCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ChkPosition", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ChkPosition(string username) {
            object[] results = this.Invoke("ChkPosition", new object[] {
                        username});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ChkPositionAsync(string username) {
            this.ChkPositionAsync(username, null);
        }
        
        /// <remarks/>
        public void ChkPositionAsync(string username, object userState) {
            if ((this.ChkPositionOperationCompleted == null)) {
                this.ChkPositionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnChkPositionOperationCompleted);
            }
            this.InvokeAsync("ChkPosition", new object[] {
                        username}, this.ChkPositionOperationCompleted, userState);
        }
        
        private void OnChkPositionOperationCompleted(object arg) {
            if ((this.ChkPositionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ChkPositionCompleted(this, new ChkPositionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ChkSection", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ChkSection(string username) {
            object[] results = this.Invoke("ChkSection", new object[] {
                        username});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ChkSectionAsync(string username) {
            this.ChkSectionAsync(username, null);
        }
        
        /// <remarks/>
        public void ChkSectionAsync(string username, object userState) {
            if ((this.ChkSectionOperationCompleted == null)) {
                this.ChkSectionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnChkSectionOperationCompleted);
            }
            this.InvokeAsync("ChkSection", new object[] {
                        username}, this.ChkSectionOperationCompleted, userState);
        }
        
        private void OnChkSectionOperationCompleted(object arg) {
            if ((this.ChkSectionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ChkSectionCompleted(this, new ChkSectionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void ChkAuthCompletedEventHandler(object sender, ChkAuthCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ChkAuthCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ChkAuthCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void ChkEmailCompletedEventHandler(object sender, ChkEmailCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ChkEmailCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ChkEmailCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void ChkDeptCompletedEventHandler(object sender, ChkDeptCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ChkDeptCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ChkDeptCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void ChkFullNameCompletedEventHandler(object sender, ChkFullNameCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ChkFullNameCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ChkFullNameCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void ChkNameCompletedEventHandler(object sender, ChkNameCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ChkNameCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ChkNameCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void ChkSurNameCompletedEventHandler(object sender, ChkSurNameCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ChkSurNameCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ChkSurNameCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void ChkPositionCompletedEventHandler(object sender, ChkPositionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ChkPositionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ChkPositionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void ChkSectionCompletedEventHandler(object sender, ChkSectionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ChkSectionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ChkSectionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591